# src/lang_utils.py

def get_text(lang):
    return {
        "tab_titles": {
            "RAG": "RAG 数据库管理" if lang == "中文" else "RAG Database",
            "Literature": "文献综述 + 问答数据库" if lang == "中文" else "Literature Review PLUS Database Q&A",
            "Anki": "Anki 记忆卡片" if lang == "中文" else "Anki Cards",
        },
        "rag_tab": {
            "header": "RAG：项目与文件管理" if lang == "中文" else "RAG: Project and File Management",
            "select_project": "选择项目：" if lang == "中文" else "Select Project:",
            "new_project": "新建项目" if lang == "中文" else "New Project",
            "project_name_placeholder": "请输入新项目名称：" if lang == "中文" else "Enter new project name:",
            "create_btn": "创建项目" if lang == "中文" else "Create Project",
            "success": "✅ 项目 {name} 创建成功！" if lang == "中文" else "✅ Project {name} created successfully!",
        },
        # 更多模块可以在这里添加，如 literature_tab, anki_tab 等
                "rag_tab": {
            "header": "RAG：项目与文件管理" if lang == "中文" else "RAG: Project and File Management",
            "select_project": "选择项目：" if lang == "中文" else "Select Project:",
            "new_project": "新建项目" if lang == "中文" else "New Project",
            "project_name_placeholder": "请输入新项目名称：" if lang == "中文" else "Enter new project name:",
            "create_btn": "创建项目" if lang == "中文" else "Create Project",
            "success": "✅ 项目 {name} 创建成功！" if lang == "中文" else "✅ Project {name} created successfully!",

            "step1_title": "### 步骤1：上传文件" if lang == "中文" else "### Step 1: Upload Files",
            "uploader_label": "上传 PDF/MD/DOCX/XLSX/HTML" if lang == "中文" else "Upload PDF/MD/DOCX/XLSX/HTML",
            "already_exists": "'{name}' 已存在。" if lang == "中文" else "'{name}' already exists.",
            "upload_success": "已上传: {files}" if lang == "中文" else "Uploaded: {files}",
            "no_new_file": "无新文件。" if lang == "中文" else "No new files.",
            "please_upload": "请上传文件。" if lang == "中文" else "Please upload files.",

            "status_title": "#### 当前分块 & 向量 状态" if lang == "中文" else "#### Current Chunk & Embedding Status",
            "embed_model": "向量模型: **{model}**" if lang == "中文" else "Embedding model: **{model}**",
            "chunk_count": "当前分块总数: **{n}**" if lang == "中文" else "Total Chunks: **{n}**",
            "embed_count": "当前向量数量: **{n}**" if lang == "中文" else "Total Embeddings: **{n}**",
            "progress_label": "向量进度（已入库/分块）" if lang == "中文" else "Embedding Progress (completed/chunks)",

            "manifest_title": "#### 📄 文件处理状态 (manifest)" if lang == "中文" else "#### 📄 File Processing Status (manifest)",
            "manifest_col_file": "文件" if lang == "中文" else "File",
            "manifest_col_nchunks": "分块数" if lang == "中文" else "Chunks",
            "manifest_col_chunkmethod": "分块方式" if lang == "中文" else "Chunk Method",
            "manifest_col_last": "最后处理" if lang == "中文" else "Last Processed",
            "no_manifest": "暂无 manifest.json，尚未预处理。" if lang == "中文" else "No manifest.json, not yet processed.",

            "step2_title": "### 步骤2：预处理文件（分块）" if lang == "中文" else "### Step 2: Preprocess Files (Chunking)",
            "chunk_method": "分块方式：" if lang == "中文" else "Chunking method:",
            "chunk_methods": ["按句子","按段落","按页","固定长度"] if lang == "中文" else ["By Sentence","By Paragraph","By Page","Fixed Length"],
            "chunk_length": "固定长度" if lang == "中文" else "Fixed Length",
            "chunk_length_label": "分块长度（字符）" if lang == "中文" else "Chunk length (chars)",
            "force_reprocess": "强制全部重新预处理（忽略 hash，适用于参数变更或修复）" if lang == "中文" else "Force full reprocessing (ignore hash; for param change/fix)",
            "start_preprocess": "开始预处理" if lang == "中文" else "Start Preprocessing",
            "preprocess_success": "预处理完成！" if lang == "中文" else "Preprocessing complete!",
            "preprocess_fail": "预处理失败: {err}" if lang == "中文" else "Preprocessing failed: {err}",

            "step3_title": "### 步骤3：生成/更新向量" if lang == "中文" else "### Step 3: Create/Update Embeddings",
            "embed_mode": "向量生成方式：" if lang == "中文" else "Embedding mode:",
            "embed_modes": ["全部重新生成向量","仅新增分块"] if lang == "中文" else ["Embed all","Only new chunks"],
            "only_new_chunks": "仅新增分块" if lang == "中文" else "Only new chunks",
            "start_embed": "生成向量" if lang == "中文" else "Generate Embeddings",
            "embed_success": "向量生成完成！" if lang == "中文" else "Embedding complete!",
            "duplicate_ids": "检测到重复ID，已跳过: {ids}" if lang == "中文" else "Duplicate IDs detected, skipped: {ids}",
            "partial_embed": "部分分块因ID重复未被生成向量，其余已完成。" if lang == "中文" else "Some chunks skipped due to duplicate IDs, others done.",
            "embed_fail": "向量生成失败: {err}" if lang == "中文" else "Embedding failed: {err}",

            "manifest_check_title": "#### 📊 Manifest 健康检查" if lang == "中文" else "#### 📊 Manifest Health Check",
            "missing_chunks": "未生成分块的文件: {files}" if lang == "中文" else "Files with no chunks: {files}",
            "all_chunked": "所有文件均已分块。" if lang == "中文" else "All files are chunked.",
        },
                "literature_tab": {
            "header": "文献综述与问答" if lang == "中文" else "Literature Review & QA",
            "step1_title": "### 步骤1：选择项目" if lang == "中文" else "### Step 1: Select Project",
            "step1_info": "请选择要进行文献综述和问答的项目，请确保已在RAG标签中上传并处理PDF。" if lang == "中文" else "Select a project to perform literature review and QA. Please make sure you have already uploaded and processed your PDFs in the RAG tab.",
            "select_project": "文献综述项目选择：" if lang == "中文" else "Select Project for Literature Review:",
            "no_project": "请先选择项目" if lang == "中文" else "Please select a project",
            "no_db_warning": "请先为该项目生成嵌入（见RAG标签）。" if lang == "中文" else "Please generate embeddings for this project first (see RAG tab).",

            "step2_title": "### 步骤2：输入检索问题" if lang == "中文" else "### Step 2: Enter Your Query",
            "step2_info": "描述你的研究问题或信息需求，系统将优化你的检索意图以获得更好结果。" if lang == "中文" else "Describe your research question or information need. The system will help you standardize and optimize your query for better retrieval.",
            "optimize_prompt": "进行检索意图优化（Prompt Optimization）" if lang == "中文" else "Prompt Optimization",
            "query_input": "请输入你的检索问题：" if lang == "中文" else "Enter Your Query:",
            "optimizing": "正在优化检索意图..." if lang == "中文" else "Prompt Optimization in progress...",
            "optimized_prompt": "优化后的检索意图: {prompt}" if lang == "中文" else "Optimized Prompt: {prompt}",

            "step3_title": "### 步骤3：编辑摘要模板" if lang == "中文" else "### Step 3: Customize Summarization Template",
            "step3_info": "你可以自定义摘要输出格式，模板支持分节及学术写作风格。" if lang == "中文" else "You can customize the output format for the summary. The template supports sections and academic writing style.",
            "default_structured": """请用以下结构进行总结：\n1. 研究背景\n2. 主要发现\n3. 挑战\n4. 未来方向\n5. 结论\n6. 关键数据或案例\n7. 参考文献""",
            "default_direct": """直接、简明地回答上述问题，仅使用上下文中的信息。如果无法明确回答，则说明“上下文信息不足”。""",
            "structured_review": "**结构化文献综述**" if lang == "中文" else "**Structured Literature Review**",
            "structured_template": "结构化模板" if lang == "中文" else "Structured Template",
            "direct_answer": "**直接回答**" if lang == "中文" else "**Direct Answer**",
            "direct_template": "直接回答模板" if lang == "中文" else "Direct Answer Template",
            "choose_template": "选择摘要模板风格：" if lang == "中文" else "Choose summary template style:",
            "structured": "结构化" if lang == "中文" else "Structured",
            "direct": "直接回答" if lang == "中文" else "Direct Answer",

            "step4_title": "### 步骤4：检索参数设置与检索" if lang == "中文" else "### Step 4: Retrieval Settings & Run Retrieval",
            "step4_info": "调整检索参数。若无结果，可适当降低相似度阈值。" if lang == "中文" else "Adjust the retrieval parameters. If you get no results, try increasing the maximum distance threshold.",
            "relevance_threshold": "最小相似度阈值：" if lang == "中文" else "Set Minimum Similarity Score (Relevance Threshold):",
            "relevance_help": "值越高匹配越严格，若无结果可适当降低。" if lang == "中文" else "Higher values mean stricter match (more similar). If you get no results, try lowering this value.",
            "num_chunks": "检索块数：" if lang == "中文" else "Select Number of Chunks to Retrieve:",
            "run_retrieval": "执行检索" if lang == "中文" else "Run Retrieval",
            "retrieving": "正在检索相关分块..." if lang == "中文" else "Retrieving relevant chunks...",
            "chunks_found": "{n} 个分块已找到" if lang == "中文" else "{n} Chunks Found",

            "step5_title": "### 步骤5：生成摘要" if lang == "中文" else "### Step 5: Summarize Retrieved Chunks",
            "step5_info": "基于检索内容和你的模板生成结构化摘要。" if lang == "中文" else "Generate a structured summary based on the retrieved content and your template.",
            "select_model": "选择模型：" if lang == "中文" else "Select Model:",
            "model_options": ["gpt-4o", "gpt-4o-mini"],
            "temperature": "Temperature (创造性)：" if lang == "中文" else "Temperature (Creativity):",
            "temp_help": "值越高输出越有创造力，常用范围0.2~1.0" if lang == "中文" else "Higher values produce more creative output. Typical range: 0.2~1.0",
            "max_tokens": "最大输出 tokens：" if lang == "中文" else "Max Tokens:",
            "max_tokens_help": "摘要输出最大token数。" if lang == "中文" else "Maximum number of tokens in the summary output.",
            "log_metrics": "记录token消耗与处理时间" if lang == "中文" else "Log Token Consumption and Processing Time",
            "generate_summary": "生成摘要" if lang == "中文" else "Generate Summary",
            "summarizing": "正在生成摘要..." if lang == "中文" else "Summarizing Retrieved Chunks...",
            "show_time": "处理用时：{time} 秒" if lang == "中文" else "Processing Time: {time} seconds",
            "show_tokens": "总 tokens：{tokens}" if lang == "中文" else "Total Tokens: {tokens}",
            "summary_fail": "摘要生成失败，请检查输入或模板。" if lang == "中文" else "Summary generation failed, please check your input and template.",
            "no_chunks": "无分块可用，请先检索。" if lang == "中文" else "No chunks found for summarization. Please run retrieval first.",
            "basic_prompt": """你获得了以下论文片段：\n\n{context}\n\n这里是你要总结的问题，仅用上下文回答，引用文献请遵循学术风格 [Chicago] 并尽量包含DOI。\n#####{query}#####\n""" if lang == "中文" else """You are given the following excerpts from research papers:\n\n{context}\n\nAnd here is the query you want to summarize, use only the information in the context.\nGenerate reference according formal academic writing style [Chicago style], include DOI whenever available.\n#####{query}#####\n""",
        },
                "anki_tab": {
            "header": "生成 Anki 卡片" if lang == "中文" else "Generate Anki Cards",
            "no_projects": "未发现项目，请先在文献分析页创建项目。" if lang == "中文" else "No projects found. Please create a project in the Literature Analysis tab first.",
            "select_project": "选择卡片项目：" if lang == "中文" else "Select Project for Cards:",
            "select_project_help": "请选择包含要制作卡片的文档的项目" if lang == "中文" else "Choose the project containing the documents you want to create cards from",
            "please_select_project": "请先选择项目" if lang == "中文" else "Please select a project",
            "preprocess_warning": "请先为该项目预处理并生成嵌入（见RAG标签）。" if lang == "中文" else "Please preprocess and embed documents in this project first (see RAG tab).",
            "using_llm": "使用大语言模型生成高质量卡片" if lang == "中文" else "Using LLM for high-quality card generation",
            "card_type": "卡片类型：" if lang == "中文" else "Card Type:",
            "qa": "问答" if lang == "中文" else "Q&A",
            "cloze": "填空" if lang == "中文" else "Cloze",
            "card_type_help": "问答卡片为问答形式，填空卡片为完型填空" if lang == "中文" else "Q&A creates question-answer pairs, Cloze creates fill-in-the-blank style cards",
            "num_cards": "生成卡片数：" if lang == "中文" else "Number of Cards:",
            "num_cards_help": "要生成多少张卡片" if lang == "中文" else "How many cards to generate",
            "difficulty": "难度：" if lang == "中文" else "Difficulty:",
            "difficulty_options": ["初级", "中级", "高级", "专家"] if lang == "中文" else ["beginner", "intermediate", "advanced", "expert"],
            "difficulty_default": "中级" if lang == "中文" else "intermediate",
            "difficulty_help": "调整卡片复杂度" if lang == "中文" else "Adjusts the complexity level of the generated cards",
            "detail_level": "细节丰富度：" if lang == "中文" else "Detail Level:",
            "detail_level_options": ["基础", "一般", "详细", "全面"] if lang == "中文" else ["basic", "moderate", "detailed", "comprehensive"],
            "detail_level_default": "一般" if lang == "中文" else "moderate",
            "detail_level_help": "控制每张卡片的信息量" if lang == "中文" else "Controls how much information to include in each card",
            "query_input": "请输入主题或知识点：" if lang == "中文" else "Enter your query:",
            "query_help": "输入你想制作卡片的主题或概念，系统会自动检索相关内容" if lang == "中文" else "Enter the topic or concept you want to create cards for. The system will find relevant content from your documents.",
            "top_k": "检索Top-K分块：" if lang == "中文" else "Top-K Chunks to Retrieve:",
            "top_k_help": "每次检索多少分块用于卡片生成" if lang == "中文" else "How many relevant chunks to retrieve for card generation",
            "relevance_threshold": "最小相似度分数：" if lang == "中文" else "Minimum Similarity Score (Relevance Threshold):",
            "relevance_threshold_help": "值越高匹配越严格，若无结果可适当降低" if lang == "中文" else "Higher values mean stricter match (more similar). If you get no results, try lowering this value.",
            "retrieve_chunks": "检索相关分块" if lang == "中文" else "Retrieve Relevant Chunks",
            "please_enter_query": "请先输入检索主题" if lang == "中文" else "Please enter a query first",
            "chunks_retrieved": "检索到 {n} 个相关分块。" if lang == "中文" else "Retrieved {n} relevant chunks.",
            "chunk_id": "**分块 {idx}:** {src}" if lang == "中文" else "**Chunk {idx}:** {src}",
            "no_chunks_found": "未检索到相关分块，请尝试降低阈值或增大Top-K。" if lang == "中文" else "No relevant chunks found. Try lowering the threshold or increasing Top-K.",
            "generate_cards": "生成卡片" if lang == "中文" else "Generate Cards",
            "please_retrieve_chunks": "请先检索相关分块" if lang == "中文" else "Please retrieve relevant chunks first",
            "generating_cards": "正在生成卡片..." if lang == "中文" else "Generating cards...",
            "llm_output": "LLM输出（CSV格式）：" if lang == "中文" else "LLM Output (CSV format):",
            "no_content_preview": "无内容可预览。" if lang == "中文" else "No content to preview.",
            "error_generating": "生成卡片出错: {err}" if lang == "中文" else "Error generating cards: {err}",
            "export_csv": "导出为CSV" if lang == "中文" else "Export to CSV",
            "csv_saved": "CSV文件已保存至: {path}" if lang == "中文" else "CSV file saved to: {path}",
            "download_cards": "下载卡片" if lang == "中文" else "Download Cards",
        }


    
    }
